### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by RileyManda** [lucas2005gao/react-non-interactive-iframe#4]
**Issue**
I am experiencing a deprecation warning in react vite.
```
WARN  Issues with peer dependencies found
.
└─┬ react-webpage-thumbnail 0.0.6
✕ unmet peer react@"^15.6.1 || ^16.0.0 || ^17.0.0": found 18.2.0
```
<img width="337" alt="Screen Shot 2023-09-30 at 10 31 51 AM" src="https://github.com/lucas2005gao/react-webpage-thumbnail/assets/37291194/c3adfd35-69d9-4cca-8c5e-056b2db22a26">

npm version : 8.11.0
node version : v16.15.0

**Comment by lucas2005gao** [comment]
The package is very simple and it should work with React 18.2. But I have prepared a new release to upgrade all dependencies and support to new versions of React 🙂
